name: Build image
on:
  push:
    branches:
      - master
    paths-ignore:
      - build.version
  repository_dispatch:
    types: [re-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version
        uses: yoichiro/gh-action-increment-value@main
        with:
          target_file: 'build.version'
          commit_message: 'bump version to: '
          target_directory: ''
          prefix: ''
          suffix: ''

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v2.6.1
      #   with:
      #     context: "${{ github.workspace }}"
      #     push: true
      #     tags: caesay/node-red:latest